title: MiuiHomeR
language: 'zh'

logo: header.png
favico: /favicon.ico?

google_analytics:
theme: jekyll-theme-minimal

github.is_project_page: true
github.owner_url: https://github.com/MiuiHomeR
github.owner_name: 薛定谔の胡桃
